### PR TITLE
migrating module base_export_security

### PR DESCRIPTION
**Pull request by dangirasv**
adding upgraded module (10->12, Model->rpc in require (.js), map object converted to list (p2->p3)

### CODE REVIEW

**Comment by dangirasv** [comment]
https://hive.versada.eu/projects/axioma-servisas/work_packages/10472/activity

**Comment by paulius-sladkevicius** [comment]
@dangirasv, please check Travis CI errors, I see there are some JS test errors https://travis-ci.org/versada/server-tools/jobs/554136604#L1789-L1862

**Review by paulius-sladkevicius — CHANGES_REQUESTED** [review]
Fix tests

**Comment by dangirasv** [comment]
There's still an issue with test_export_visibility (Java Script test), which I cannot resolve

**Review by paulius-sladkevicius — APPROVED** [review]
lets leave for now JS tests, however needs somewhere to mention that they are not fixed yet. Mainly because JS part changed a lot from v10.

**Pull request merged**
